### PR TITLE
Create Assignment2_Script.sql

### PR DESCRIPTION
**Pull request by Ashok-Ab4**
Install All the necessary database files and run the SQL queries to get the required outputs!

### CODE REVIEW

**Comment by kratipatidar** [comment]
Good work on the code. I have the following questions/suggestions/corrections-

1. Your tables for the first two questions, annual and historic batting average are displaying null columns along with the desired columns. That is because when you are creating a new table to store the results, you're creating new columns as well. You don't need to do that, since you're already selecting columns into your table. 

You could directly do-
create table historic_ba as (look at my code for reference)

2. There was a missing comma in the last line, after batter, when you were creating a new table to compute the rolling average (not to store the results). I have included the code for reference. Just correct that and then you are set.

CREATE OR REPLACE TABLE batters 
SELECT batter,atBat , Hit , b.game_id , local_date
FROM batter_counts b JOIN game g ON b.game_id = g.game_id 
ORDER BY batter game_id ,local_date ;

**Comment by Ashok-Ab4** [comment]
> Good work on the code. I have the following questions/suggestions/corrections-
> 
> 1. Your tables for the first two questions, annual and historic batting average are displaying null columns along with the desired columns. That is because when you are creating a new table to store the results, you're creating new columns as well. You don't need to do that, since you're already selecting columns into your table.
> 
> You could directly do-
> create table historic_ba as (look at my code for reference)
> 
> 1. There was a missing comma in the last line, after batter, when you were creating a new table to compute the rolling average (not to store the results). I have included the code for reference. Just correct that and then you are set.
> 
> CREATE OR REPLACE TABLE batters
> SELECT batter,atBat , Hit , b.game_id , local_date
> FROM batter_counts b JOIN game g ON b.game_id = g.game_id
> ORDER BY batter game_id ,local_date ;

Good catch! saved me a couple of points there 
Made the changes let me know if it looks alright to you now!

**Comment by kratipatidar** [comment]
I think it's look good now. Still doubtful about how we chose to tackle nulls, but yes, we'll leave that to the prof's discretion.

**Review by kratipatidar — APPROVED** [review]

**Review by dafrenchyman — APPROVED** [review]
Please check the comments I gave you for the assignment in Canvas. Once you’ve addressed those issues (if any) please merge the PR in!

**Pull request merged**
